import { expect, test } from '@playwright/test'
import { screenshot, showCaption } from './helpers/captions'

const isDemoMode = process.env.E2E_MODE === 'demo'

test.describe('Demostraci\u00f3n visual del ERP sin servicios externos', () => {
  test.skip(!isDemoMode, 'Esta prueba se ejecuta exclusivamente con E2E_MODE=demo.')

  test('recorre los flujos del modo demo, roles, agente y WhatsApp simulado', async ({ page }) => {
    await page.goto('/login')
    await showCaption(page, 'Entorno Demo \u2014 ERP autocontenido en el navegador', 2_300)
    await expect(page.getByText(/MODO DEMO/)).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Acceso de demostración' })).toBeVisible()
    await expect(page.getByText('Credenciales exclusivas del entorno de evaluación.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Usar administrador demo' }).click()
    await expect(page.getByLabel('Correo')).toHaveValue('admin@supermercado.demo')
    await expect(page.getByLabel('Contraseña')).toHaveValue('AdminDemo2026!')
    await screenshot(page, 'demo-01-login.png')
    await page.getByRole('button', { name: 'Iniciar sesión' }).click()
    await expect(page).toHaveURL(/\/dashboard/)
    await expect(page.getByTitle('Entorno de demostraci\u00f3n \u2014 datos almacenados localmente')).toBeVisible()

    await showCaption(page, 'Administrador Demo \u2014 dashboard y datos almacenados localmente')
    await expect(page.getByText('Ventas hoy', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-02-dashboard.png')

    await page.once('dialog', async (dialog) => {
      expect(dialog.message()).toContain('Restablecer')
      await dialog.dismiss()
    })
    await page.getByRole('button', { name: 'Restablecer datos demo' }).click()

    await showCaption(page, 'Inventario Demo \u2014 cat\u00e1logo oficial de 100 productos')
    await page.getByRole('link', { name: 'Inventario', exact: true }).click()
    const search = page.locator('input.search')
    await search.fill('FRV-001')
    await expect(page.getByRole('cell', { name: 'Tomate saladet' })).toBeVisible()
    await expect(page.getByText('120 kg', { exact: true })).toBeVisible()
    await expect(page.getByText('Catálogo oficial cargado: 100 productos', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-03-inventory.png')

    await showCaption(page, 'Administrador Demo \u2014 edici\u00f3n y ajuste de inventario')
    await page.getByRole('button', { name: 'Editar producto' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByLabel('Umbral de stock bajo').fill('120')
    await page.getByRole('button', { name: 'Guardar cambios' }).click()
    await expect(page.getByText('Producto actualizado.', { exact: true })).toBeVisible()
    await search.fill('FRV-002')
    await page.getByRole('button', { name: 'Ajustar' }).click()
    await page.getByLabel('Cantidad').fill('1')
    await page.getByLabel('Motivo').selectOption({ label: 'Correcci\u00f3n' })
    await page.getByRole('button', { name: 'Confirmar ajuste' }).click()
    await expect(page.getByText('Movimiento registrado.', { exact: true })).toBeVisible()

    await showCaption(page, 'POS Demo \u2014 Tomate saladet, 0.750 kg, cobro y cambio')
    await page.getByRole('link', { name: 'Punto de venta', exact: true }).click()
    await page.locator('input.search').fill('FRV-001')
    await page.getByRole('button', { name: /Tomate saladet/ }).click()
    await page.getByLabel('Cantidad Tomate saladet').fill('0.750')
    await expect(page.getByText('$21.38', { exact: true }).first()).toBeVisible()
    await page.getByLabel('Efectivo recibido').fill('50.00')
    await expect(page.getByText('Cambio: $28.62', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-04-pos.png')
    await page.getByRole('button', { name: 'Cobrar venta' }).click()
    await expect(page.getByText('Ticket de venta', { exact: true })).toBeVisible()
    await expect(page.getByText(/MODO DEMO/)).toBeVisible()
    await screenshot(page, 'demo-05-ticket.png')
    await page.getByRole('button', { name: 'Nueva venta' }).click()

    await showCaption(page, 'Inventario Demo \u2014 stock, venta y movimiento persistidos')
    await page.getByRole('link', { name: 'Inventario', exact: true }).click()
    await expect(page).toHaveURL(/\/inventario/)
    await page.reload()
    await page.locator('input.search').fill('FRV-001')
    await expect(page.getByRole('cell', { name: /119\.25 kg/ })).toBeVisible()
    await page.getByLabel('Sólo stock bajo').check()
    await expect(page.getByRole('cell', { name: 'Tomate saladet' })).toBeVisible()
    await page.getByRole('button', { name: 'Movimientos' }).click()
    await page.locator('input.search').fill('Tomate')
    await expect(page.getByText('Venta POS', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-06-movement.png')

    await showCaption(page, 'Finanzas Demo \u2014 ventas, gasto, flujo y productos m\u00e1s vendidos')
    await page.getByRole('link', { name: 'Finanzas', exact: true }).click()
    await expect(page.getByText('Ventas de hoy', { exact: true })).toBeVisible()
    await page.getByLabel('Categor\u00eda').selectOption('otros')
    await page.getByLabel('Descripci\u00f3n').fill('Validaci\u00f3n E2E modo demo')
    await page.getByLabel('Monto').fill('10.00')
    await page.getByRole('button', { name: 'Guardar gasto' }).click()
    await expect(page.getByText('Gasto registrado.', { exact: true })).toBeVisible()
    await expect(page.getByText('Tomate saladet', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-07-finance.png')

    await showCaption(page, 'Agente de negocio \u2014 modo demo, consultando datos del ERP')
    await page.getByRole('link', { name: 'Resumen' }).click()
    await page.getByLabel('Pregunta al agente demo').fill('\u00bfCu\u00e1nto vendimos hoy?')
    await page.getByRole('button', { name: 'Consultar' }).click()
    await expect(page.locator('.demo-answer')).toHaveText('Ventas del periodo: $21.38.')
    await screenshot(page, 'demo-08-agent.png')

    await showCaption(page, 'WhatsApp \u2014 simulaci\u00f3n de integraci\u00f3n')
    await page.getByRole('button', { name: 'Simular mensaje' }).click()
    await expect(page.locator('.whatsapp-bubble.outgoing')).toContainText('Ventas del periodo: $21.38.')
    await screenshot(page, 'demo-09-whatsapp.png')

    await showCaption(page, 'Cajero Demo \u2014 POS y consulta de inventario, sin acceso administrativo')
    await page.getByRole('button', { name: 'Cerrar sesi\u00f3n' }).click()
    await expect(page).toHaveURL(/\/login/)
    await page.getByRole('button', { name: 'Usar cajero demo' }).click()
    await expect(page.getByLabel('Correo')).toHaveValue('cajero@supermercado.demo')
    await expect(page.getByLabel('Contraseña')).toHaveValue('CajeroDemo2026!')
    await page.getByRole('button', { name: 'Iniciar sesión' }).click()
    await expect(page).toHaveURL(/\/pos/)
    await page.getByRole('link', { name: 'Inventario', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Editar producto' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Ajustar' })).toHaveCount(0)
    await page.goto('/dashboard')
    await expect(page).toHaveURL(/\/pos/)
    await page.goto('/finanzas')
    await expect(page).toHaveURL(/\/pos/)
    await screenshot(page, 'demo-10-cashier.png')
    await showCaption(page, 'Entorno Demo validado \u2014 sin Supabase, IA ni WhatsApp externos', 2_500)
  })
})
