import { expect, test } from '@playwright/test'
import { finalScreenshot, screenshot, showCaption } from './helpers/captions'
import { checkVisualIntegrity } from './helpers/visual'

const isDemoMode = process.env.E2E_MODE === 'demo'

test.use({ viewport: { width: 1440, height: 900 } })

test.describe('Demostración visual del ERP sin servicios externos', () => {
  test.skip(!isDemoMode, 'Esta prueba se ejecuta exclusivamente con E2E_MODE=demo.')

  test('recorre los flujos del modo demo, roles, agente y WhatsApp simulado', async ({ page }) => {
    await page.goto('/login')
    await showCaption(page, 'Entorno Demo — ERP autocontenido para evaluación', 2_300)
    await expect(page.getByText(/MODO DEMO/)).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Accesos para evaluación' })).toBeVisible()
    await expect(page.getByText('Credenciales exclusivas del entorno de evaluación.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Usar administrador demo' }).click()
    await expect(page.getByLabel('Correo')).toHaveValue('admin@supermercado.demo')
    await expect(page.getByLabel('Contraseña')).toHaveValue('AdminDemo2026!')
    await screenshot(page, 'demo-01-login.png')
    await finalScreenshot(page, '01-login.png')
    await checkVisualIntegrity(page, 'Login 1440x900')
    await page.getByRole('button', { name: 'Iniciar sesión' }).click()
    await expect(page).toHaveURL(/\/dashboard/)
    await expect(page.getByTitle('Modo de demostración')).toBeVisible()

    await showCaption(page, 'Administrador Demo — indicadores, inventario y operaciones')
    await expect(page.getByText('Ventas hoy', { exact: true })).toBeVisible()
    await expect(page.getByText('Producto más vendido', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-02-dashboard.png')
    await finalScreenshot(page, '02-dashboard.png')
    await checkVisualIntegrity(page, 'Dashboard 1440x900')

    await page.once('dialog', async (dialog) => {
      expect(dialog.message()).toContain('Restablecer')
      await dialog.dismiss()
    })
    await page.getByRole('button', { name: 'Restablecer datos demo' }).click()

    await showCaption(page, 'Inventario Demo — catálogo oficial de 100 productos')
    await page.getByRole('link', { name: 'Inventario', exact: true }).click()
    const search = page.locator('input.search')
    await search.fill('FRV-001')
    await expect(page.getByRole('cell', { name: 'Tomate saladet' })).toBeVisible()
    await expect(page.getByText('120 kg', { exact: true })).toBeVisible()
    await expect(page.getByText('Catálogo oficial cargado: 100 productos', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-03-inventory.png')

    await showCaption(page, 'Administrador Demo — edición y ajuste de inventario')
    await page.getByRole('button', { name: 'Editar producto' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByLabel('Umbral de stock bajo').fill('120')
    await page.getByRole('button', { name: 'Guardar cambios' }).click()
    await expect(page.getByText('Producto actualizado.', { exact: true })).toBeVisible()
    await search.fill('FRV-002')
    await page.getByRole('button', { name: 'Ajustar' }).click()
    await page.getByLabel('Cantidad').fill('1')
    await page.getByLabel('Motivo').selectOption({ label: 'Corrección' })
    await page.getByRole('button', { name: 'Confirmar ajuste' }).click()
    await expect(page.getByText('Movimiento registrado.', { exact: true })).toBeVisible()

    await showCaption(page, 'POS Demo — Tomate saladet, 0.750 kg, cobro y cambio')
    await page.getByRole('link', { name: 'Punto de venta', exact: true }).click()
    await finalScreenshot(page, '03-pos.png')
    await checkVisualIntegrity(page, 'POS vacío 1440x900')
    await page.locator('input.search').fill('FRV-001')
    await page.getByRole('button', { name: /Tomate saladet/ }).click()
    await page.getByLabel('Cantidad Tomate saladet').fill('0.750')
    await expect(page.getByText('$21.38', { exact: true }).first()).toBeVisible()
    await page.getByLabel('Efectivo recibido').fill('50.00')
    await expect(page.getByText('Cambio: $28.62', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-04-pos.png')
    await finalScreenshot(page, '04-pos-weight.png')
    await checkVisualIntegrity(page, 'POS por peso 1440x900')
    await page.getByRole('button', { name: 'Cobrar venta' }).click()
    await expect(page.getByText('Ticket de venta', { exact: true })).toBeVisible()
    await expect(page.getByText(/MODO DEMO/)).toBeVisible()
    await screenshot(page, 'demo-05-ticket.png')
    await finalScreenshot(page, '05-ticket.png')
    await checkVisualIntegrity(page, 'Ticket 1440x900')
    await page.getByRole('button', { name: 'Nueva venta' }).click()

    await showCaption(page, 'Inventario Demo — stock, venta y movimiento persistidos')
    await page.getByRole('link', { name: 'Inventario', exact: true }).click()
    await expect(page).toHaveURL(/\/inventario/)
    await page.reload()
    await page.locator('input.search').fill('FRV-001')
    await expect(page.getByRole('cell', { name: /119\.25 kg/ })).toBeVisible()
    await finalScreenshot(page, '06-inventory.png')
    await checkVisualIntegrity(page, 'Inventario 1440x900')
    await page.getByLabel('Sólo stock bajo').check()
    await expect(page.getByRole('cell', { name: 'Tomate saladet' })).toBeVisible()
    await page.getByRole('button', { name: 'Movimientos' }).click()
    await page.locator('input.search').fill('Tomate')
    await expect(page.getByText('Venta POS', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-06-movement.png')
    await finalScreenshot(page, '07-movements.png')
    await checkVisualIntegrity(page, 'Movimientos 1440x900')

    await showCaption(page, 'Finanzas Demo — ventas, gasto, flujo y productos más vendidos')
    await page.getByRole('link', { name: 'Finanzas', exact: true }).click()
    await expect(page.getByText('Ventas de hoy', { exact: true })).toBeVisible()
    await page.getByLabel('Categoría').selectOption('otros')
    await page.getByLabel('Descripción').fill('Validación E2E modo demo')
    await page.getByLabel('Monto').fill('10.00')
    await page.getByRole('button', { name: 'Guardar gasto' }).click()
    await expect(page.getByText('Gasto registrado.', { exact: true })).toBeVisible()
    await expect(page.getByText('Tomate saladet', { exact: true })).toBeVisible()
    await screenshot(page, 'demo-07-finance.png')
    await finalScreenshot(page, '08-finance.png')
    await checkVisualIntegrity(page, 'Finanzas 1440x900')

    await showCaption(page, 'Asistente del negocio — consultas con datos del ERP')
    await page.getByRole('link', { name: 'Dashboard' }).click()
    await page.getByLabel('Pregunta al asistente').fill('¿Cuánto vendimos hoy?')
    await page.getByRole('button', { name: 'Consultar' }).click()
    await expect(page.locator('.demo-answer')).toHaveText('Ventas del periodo: $21.38.')
    await screenshot(page, 'demo-08-agent.png')
    await finalScreenshot(page, '09-agent.png')
    await checkVisualIntegrity(page, 'Asistente 1440x900')

    await showCaption(page, 'WhatsApp — simulación de consulta del negocio')
    await page.getByRole('button', { name: 'Simular mensaje' }).click()
    await expect(page.locator('.whatsapp-bubble.outgoing')).toContainText('Ventas del periodo: $21.38.')
    await screenshot(page, 'demo-09-whatsapp.png')
    await finalScreenshot(page, '10-whatsapp-demo.png')
    await checkVisualIntegrity(page, 'WhatsApp demo 1440x900')

    await showCaption(page, 'Cajero Demo — POS e inventario de consulta, sin acceso administrativo')
    await page.getByRole('button', { name: 'Cerrar sesión' }).click()
    await expect(page).toHaveURL(/\/login/)
    await page.getByRole('button', { name: 'Usar cajero demo' }).click()
    await expect(page.getByLabel('Correo')).toHaveValue('cajero@supermercado.demo')
    await expect(page.getByLabel('Contraseña')).toHaveValue('CajeroDemo2026!')
    await page.getByRole('button', { name: 'Iniciar sesión' }).click()
    await expect(page).toHaveURL(/\/pos/)
    await page.getByRole('link', { name: 'Inventario', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Editar producto' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Ajustar' })).toHaveCount(0)
    await finalScreenshot(page, '11-cashier.png')
    await checkVisualIntegrity(page, 'Inventario cajero 1440x900')
    await page.goto('/dashboard')
    await expect(page).toHaveURL(/\/pos/)
    await page.goto('/finanzas')
    await expect(page).toHaveURL(/\/pos/)
    await screenshot(page, 'demo-10-cashier.png')
    await finalScreenshot(page, '12-cashier-restricted.png')
    await checkVisualIntegrity(page, 'Restricción cajero 1440x900')
    await showCaption(page, 'Entorno Demo validado — recorrido disponible para evaluación', 2_500)
  })
})
