'use client'
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import DemoPos from '@/components/demo/demo-pos'
import { isDemoMode } from '@/lib/supabase/config'
import type { CartItem, Product } from '@/types/database'
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n||0)
const roundMoney=(n:number)=>Math.round((n+Number.EPSILON)*100)/100
type Ticket={folio:string;date:Date;cashier:string;items:CartItem[];total:number;received:number;change:number}
export default function Pos(){if(isDemoMode())return <DemoPos/>;return <SupabasePos/>}
function SupabasePos(){const [db]=useState(()=>createClient());const [products,setProducts]=useState<Product[]>([]);const [q,setQ]=useState('');const [cart,setCart]=useState<CartItem[]>([]);const [cash,setCash]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(false);const [cashier,setCashier]=useState('');const [ticket,setTicket]=useState<Ticket|null>(null)
 async function load(){const {data}=await db.from('products').select('*').eq('active',true).order('name');setProducts((data??[]) as Product[])}
 useEffect(()=>{void load();void db.auth.getUser().then(async({data:{user}})=>{if(!user)return;const {data}=await db.from('profiles').select('full_name').eq('id',user.id).single();setCashier(data?.full_name??'Cajero')})},[])
 const results=products.filter(p=>(p.name+p.sku).toLowerCase().includes(q.toLowerCase())).slice(0,20);const total=roundMoney(cart.reduce((sum,product)=>sum+roundMoney(product.price*product.quantity),0));const received=Number(cash)||0
 function add(p:Product){setNotice('');setCart(x=>{const found=x.find(i=>i.id===p.id);if(found&&found.quantity+1>p.stock){setNotice(`Stock insuficiente para ${p.name}.`);return x}return found?x.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...x,{...p,quantity:1}]})}
 function qty(id:string,value:string){const quantity=Number(value);const product=cart.find(i=>i.id===id);if(!product||!Number.isFinite(quantity)||quantity<=0){setNotice('La cantidad debe ser mayor a cero.');return}if(product.unit!=='kg'&&!Number.isInteger(quantity)){setNotice(`${product.name} sólo permite cantidades enteras.`);return}if(quantity>product.stock){setNotice(`No hay suficiente stock para ${product.name}.`);return}setNotice('');setCart(x=>x.map(i=>i.id===id?{...i,quantity}:i))}
 async function charge(){setNotice('');if(!cart.length||received<total){setNotice('El efectivo recibido debe cubrir el total.');return}setLoading(true);const items=cart.map(x=>({...x}));const {data,error}=await db.rpc('complete_sale',{p_items:items.map(x=>({product_id:x.id,quantity:x.quantity})),p_amount_received:received});setLoading(false);if(error){setNotice(error.message);return}const response=data as {sale_id:string;change_amount:number};setTicket({folio:response.sale_id.slice(0,8).toUpperCase(),date:new Date(),cashier,items,total,received,change:Number(response.change_amount)});setCart([]);setCash('');void load()}
 if(ticket)return <TicketView ticket={ticket} onNew={()=>setTicket(null)}/>
 return <div className="pos"><section className="card"><input className="search" autoFocus placeholder="Busca por producto o SKU" value={q} onChange={e=>setQ(e.target.value)}/><div className="product-grid">{results.map(p=><button className="product" key={p.id} onClick={()=>add(p)}><strong>{p.name}</strong><small>{p.sku} · {p.stock} {p.unit}</small><b>{money(p.price)} / {p.unit}</b></button>)}</div></section><section className="card cart"><h3>Venta actual</h3>{cart.length===0?<p className="muted">Agrega productos para comenzar.</p>:cart.map(i=><div className="cart-line" key={i.id}><div><strong>{i.name}</strong><small>{money(i.price)} / {i.unit}</small></div><input aria-label={`Cantidad ${i.name}`} type="number" min={i.unit==='kg'?'0.001':'1'} step={i.unit==='kg'?'0.001':'1'} max={i.stock} value={i.quantity} onChange={e=>qty(i.id,e.target.value)}/><b>{money(roundMoney(i.price*i.quantity))}</b><button className="icon" onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}>×</button></div>)}<div className="totals"><span>Total</span><strong>{money(total)}</strong></div><label>Efectivo recibido<input type="number" min={total} step="0.01" value={cash} onChange={e=>setCash(e.target.value)} /></label><p className="change">Cambio: {money(Math.max(0,received-total))}</p>{notice&&<p className="notice">{notice}</p>}<button onClick={charge} disabled={loading||!cart.length}>{loading?'Procesando…':'Cobrar venta'}</button>{cart.length>0&&<button className="secondary" onClick={()=>setCart([])}>Vaciar carrito</button>}</section></div>}
function TicketView({ticket,onNew}:{ticket:Ticket;onNew:()=>void}){return <section className="ticket card"><div className="ticket-print"><p className="eyebrow">MERCADO CENTRAL</p><h2>Ticket de venta</h2><p>Folio: <strong>{ticket.folio}</strong><br/>{new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(ticket.date)}<br/>Cajero: {ticket.cashier}</p><table><thead><tr><th>Producto</th><th>Cantidad</th><th>P. unit.</th><th>Subtotal</th></tr></thead><tbody>{ticket.items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.quantity.toFixed(x.unit==='kg'?3:0)} {x.unit}</td><td>{money(x.price)}</td><td>{money(roundMoney(x.price*x.quantity))}</td></tr>)}</tbody></table><div className="ticket-totals"><p>Total <strong>{money(ticket.total)}</strong></p><p>Efectivo {money(ticket.received)}</p><p>Cambio <strong>{money(ticket.change)}</strong></p></div></div><div className="ticket-actions"><button onClick={onNew}>Nueva venta</button><button className="secondary" onClick={()=>window.print()}>Imprimir</button></div></section>}
