'use client'
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n||0)
type Expense={id:string;category:string;description:string;amount:number;expense_date:string;profiles:{full_name:string}|null}
type Top={name:string;quantity:number;income:number}
function periods(){const now=new Date();return {today:now.toISOString().slice(0,10),week:new Date(now.getTime()-6*864e5).toISOString(),month:new Date(now.getFullYear(),now.getMonth(),1).toISOString()}}
export default function Finance(){const [db]=useState(()=>createClient());const [sales,setSales]=useState({today:0,week:0,month:0});const [expenses,setExpenses]=useState(0);const [history,setHistory]=useState<Expense[]>([]);const [top,setTop]=useState<Top[]>([]);const [period,setPeriod]=useState<'today'|'week'|'month'>('week');const [message,setMessage]=useState('');const [form,setForm]=useState({category:'otros',description:'',amount:'',expense_date:new Date().toISOString().slice(0,10)})
 async function load(){const p=periods();const [{data:allSales},{data:allExpenses},{data:expenseRows},{data:periodSales}]=await Promise.all([db.from('sales').select('id,total,created_at').gte('created_at',p.month),db.from('expenses').select('amount').gte('expense_date',p.month),db.from('expenses').select('id,category,description,amount,expense_date,profiles(full_name)').order('expense_date',{ascending:false}).limit(25),db.from('sales').select('id').gte('created_at',p[period])]);const sum=(date:string)=>(allSales??[]).filter(s=>s.created_at>=date).reduce((a,s)=>a+Number(s.total),0);setSales({today:sum(p.today),week:sum(p.week),month:sum(p.month)});setExpenses((allExpenses??[]).reduce((a,x)=>a+Number(x.amount),0));setHistory((expenseRows??[]) as unknown as Expense[]);const ids=(periodSales??[]).map(s=>s.id);if(!ids.length){setTop([]);return}const {data:items}=await db.from('sale_items').select('quantity,subtotal,products(name)').in('sale_id',ids);const grouped=new Map<string,Top>();for(const item of items??[]){const name=(item.products as unknown as {name:string}|null)?.name??'Producto';const current=grouped.get(name)??{name,quantity:0,income:0};current.quantity+=Number(item.quantity);current.income+=Number(item.subtotal);grouped.set(name,current)}setTop([...grouped.values()].sort((a,b)=>b.quantity-a.quantity).slice(0,5))}
 useEffect(()=>{void load()},[period])
 async function save(e:React.FormEvent){e.preventDefault();const amount=Number(form.amount);if(!form.description.trim()||!Number.isFinite(amount)||amount<=0){setMessage('Captura una descripción y monto válidos.');return}const {data:{user}}=await db.auth.getUser();if(!user)return;const {error}=await db.from('expenses').insert({...form,amount,created_by:user.id});setMessage(error?`Error: ${error.message}`:'Gasto registrado.');if(!error){setForm({...form,description:'',amount:''});void load()}}
 return <><section><p className="section-label">VENTAS</p><div className="metrics"><Metric label="Ventas de hoy" value={money(sales.today)}/><Metric label="Ventas esta semana" value={money(sales.week)}/><Metric label="Ventas este mes" value={money(sales.month)}/></div></section><section><p className="section-label">FLUJO</p><div className="metrics"><Metric label="Ingresos" value={money(sales.month)}/><Metric label="Egresos" value={money(expenses)}/><Metric label="Flujo neto" value={money(sales.month-expenses)}/></div></section><div className="finance-grid"><section className="card"><p className="section-label">GASTOS</p><h3>Registrar gasto</h3><form onSubmit={save} className="form"><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['renta','electricidad','proveedores','mantenimiento','otros'].map(x=><option key={x}>{x}</option>)}</select></label><label>Descripción<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Monto<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Fecha<input type="date" value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></label><button>Guardar gasto</button>{message&&<p className="notice">{message}</p>}</form></section><section className="card table-wrap"><p className="section-label">GASTOS</p><h3>Historial reciente</h3><table><thead><tr><th>Fecha</th><th>Categoría</th><th>Descripción</th><th>Monto</th><th>Usuario</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.expense_date}</td><td>{x.category}</td><td>{x.description}</td><td>{money(x.amount)}</td><td>{x.profiles?.full_name??'—'}</td></tr>)}</tbody></table></section></div><section className="card table-wrap"><div className="table-title"><div><p className="section-label">TOP PRODUCTOS</p><h3>Productos más vendidos</h3></div><select className="period-select" value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="today">Hoy</option><option value="week">Semana</option><option value="month">Mes</option></select></div><table><thead><tr><th>Producto</th><th>Cantidad vendida</th><th>Ingresos generados</th></tr></thead><tbody>{top.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.quantity}</td><td>{money(x.income)}</td></tr>)}</tbody></table>{!top.length&&<p className="muted">No encontré datos para este periodo.</p>}</section></>}
function Metric({label,value}:{label:string;value:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}
